// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeAKiaVcYGLfrO_sfl6L5MSe6SHDfQWoA',
    appId: '1:309785311155:web:42b83b9d1b618c73ac7dc6',
    messagingSenderId: '309785311155',
    projectId: 'ankon12',
    authDomain: 'ankon12.firebaseapp.com',
    storageBucket: 'ankon12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9zSfsFkSKh_T6cmyPz8Zvhr0plGxvh40',
    appId: '1:309785311155:android:2055fa8a1d9c8738ac7dc6',
    messagingSenderId: '309785311155',
    projectId: 'ankon12',
    storageBucket: 'ankon12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe1E2IjU4j24T_GcQ0rs1BGjRVDH2nFgY',
    appId: '1:309785311155:ios:fbc9fc1ae26b4bb9ac7dc6',
    messagingSenderId: '309785311155',
    projectId: 'ankon12',
    storageBucket: 'ankon12.appspot.com',
    iosBundleId: 'com.example.note',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe1E2IjU4j24T_GcQ0rs1BGjRVDH2nFgY',
    appId: '1:309785311155:ios:a385bb5306d69ec7ac7dc6',
    messagingSenderId: '309785311155',
    projectId: 'ankon12',
    storageBucket: 'ankon12.appspot.com',
    iosBundleId: 'com.example.note.RunnerTests',
  );
}
